version: 2.1

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:17.0.7

      - image: cimg/postgres:12.15

    working_directory: ~/api

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      # create gradle cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "api/build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: gradle -p api dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "api/build.gradle" }}

      # run tests!
      - run: gradle -p api test
      - run: curl localhost:5432

