version: 2.1

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:17.0.7

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/api

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      # create gradle cache
      - run: ls -la
      - run: ls -la api/
      - restore_cache:
          paths:
            - ~/api/api/.gradle
          keys:
            - v1-dependencies-{{ checksum "api/build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: gradle -p api dependencies
      - run: ls -la
      - run: ls -la api/
      - save_cache:
          paths:
            - ~/api/api/.gradle
          key: v1-dependencies-{{ checksum "api/build.gradle" }}

      # run tests!
      - run: gradle -p api test
